In [10]:
import numpy as np
import math



In [2]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [3]:
k=np.linspace(2.0, 3.0, num=5)

In [4]:
k

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [5]:
print(k)

[2.   2.25 2.5  2.75 3.  ]


In [6]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [10]:
np.linspace(0, 0.01, int(0.01 * 10000),axis=0)



array([0.        , 0.00010101, 0.00020202, 0.00030303, 0.00040404,
       0.00050505, 0.00060606, 0.00070707, 0.00080808, 0.00090909,
       0.0010101 , 0.00111111, 0.00121212, 0.00131313, 0.00141414,
       0.00151515, 0.00161616, 0.00171717, 0.00181818, 0.00191919,
       0.0020202 , 0.00212121, 0.00222222, 0.00232323, 0.00242424,
       0.00252525, 0.00262626, 0.00272727, 0.00282828, 0.00292929,
       0.0030303 , 0.00313131, 0.00323232, 0.00333333, 0.00343434,
       0.00353535, 0.00363636, 0.00373737, 0.00383838, 0.00393939,
       0.0040404 , 0.00414141, 0.00424242, 0.00434343, 0.00444444,
       0.00454545, 0.00464646, 0.00474747, 0.00484848, 0.00494949,
       0.00505051, 0.00515152, 0.00525253, 0.00535354, 0.00545455,
       0.00555556, 0.00565657, 0.00575758, 0.00585859, 0.0059596 ,
       0.00606061, 0.00616162, 0.00626263, 0.00636364, 0.00646465,
       0.00656566, 0.00666667, 0.00676768, 0.00686869, 0.0069697 ,
       0.00707071, 0.00717172, 0.00727273, 0.00737374, 0.00747

In [11]:
k=[1,2]

In [12]:
k.extend(3,4)



TypeError: list.extend() takes exactly one argument (2 given)

In [13]:
k.extend(3)

TypeError: 'int' object is not iterable

In [14]:
k.extend([3,4])

In [16]:
t=np.linspace(0, 0.01, int(0.01 * 10000),axis=0)


In [17]:
s = np.sqrt(2 * 0.001 / 0.01) * np.cos(2 * np.pi * 100 * t)

In [18]:
s

array([ 0.4472136 ,  0.44631321,  0.44361568,  0.43913186,  0.43287982,
        0.42488472,  0.41517876,  0.40380102,  0.39079732,  0.37622002,
        0.36012781,  0.34258549,  0.3236637 ,  0.30343863,  0.28199173,
        0.25940934,  0.2357824 ,  0.21120605,  0.18577924,  0.15960437,
        0.13278683,  0.1054346 ,  0.07765783,  0.04956835,  0.02127928,
       -0.00709547, -0.03544166, -0.06364513, -0.09159233, -0.11917071,
       -0.14626924, -0.17277879, -0.19859263, -0.2236068 , -0.24772058,
       -0.27083689, -0.29286262, -0.31370911, -0.33329239, -0.35153363,
       -0.36835937, -0.38370185, -0.3974993 , -0.40969616, -0.42024332,
       -0.4290983 , -0.43622546, -0.4415961 , -0.44518858, -0.44698844,
       -0.44698844, -0.44518858, -0.4415961 , -0.43622546, -0.4290983 ,
       -0.42024332, -0.40969616, -0.3974993 , -0.38370185, -0.36835937,
       -0.35153363, -0.33329239, -0.31370911, -0.29286262, -0.27083689,
       -0.24772058, -0.2236068 , -0.19859263, -0.17277879, -0.14

In [23]:
k=np.cos(2 * np.pi * 100 * t)
print(k)

[ 1.          0.99798668  0.99195481  0.9819287   0.9679487   0.95007112
  0.92836793  0.90292654  0.87384938  0.84125353  0.80527026  0.76604444
  0.72373404  0.67850941  0.63055267  0.58005691  0.52722547  0.47227107
  0.41541501  0.35688622  0.29692038  0.23575894  0.17364818  0.1108382
  0.04758192 -0.01586596 -0.07924996 -0.14231484 -0.20480667 -0.26647381
 -0.32706796 -0.38634513 -0.44406661 -0.5        -0.55392006 -0.60560969
 -0.65486073 -0.70147489 -0.74526445 -0.78605309 -0.82367658 -0.85798341
 -0.88883545 -0.91610846 -0.93969262 -0.95949297 -0.97542979 -0.98743889
 -0.99547192 -0.99949654 -0.99949654 -0.99547192 -0.98743889 -0.97542979
 -0.95949297 -0.93969262 -0.91610846 -0.88883545 -0.85798341 -0.82367658
 -0.78605309 -0.74526445 -0.70147489 -0.65486073 -0.60560969 -0.55392006
 -0.5        -0.44406661 -0.38634513 -0.32706796 -0.26647381 -0.20480667
 -0.14231484 -0.07924996 -0.01586596  0.04758192  0.1108382   0.17364818
  0.23575894  0.29692038  0.35688622  0.41541501  0.

In [59]:

# Python3 code to demonstrate working of
# Converting binary to string
# Using BinarytoDecimal(binary)+chr()


# Defining BinarytoDecimal() function
def BinaryToDecimal(binary):
		
	binary1 = binary
	decimal, i, n = 0, 0, 0
	while(binary != 0):
		dec = binary % 10
		decimal = decimal + dec * pow(2, i)
		binary = binary//10
		i += 1
	return (decimal)

# Driver's code
# initializing binary data
#bin_data ='100001111010001101111110001111010111100001'
bin_data='100001111010001101111110001111010111100001'

# print binary data
print("The binary value is:", bin_data)

# initializing a empty string for
# storing the string data
str_data =''

# slicing the input and converting it
# in decimal and then converting it in string
for i in range(0, len(bin_data), 7):
	
	# slicing the bin_data from index range [0, 6]
	# and storing it as integer in temp_data
	temp_data = int(bin_data[i:i + 7])
	
	# passing temp_data in BinarytoDecimal() function
	# to get decimal value of corresponding temp_data
	decimal_data = BinaryToDecimal(temp_data)
	
	# Decoding the decimal value returned by
	# BinarytoDecimal() function, using chr()
	# function which return the string corresponding
	# character for given ASCII value, and store it
	# in str_data
	str_data = str_data + chr(decimal_data)

# printing the result
print("The Binary value after string conversion is:",
	str_data)


The binary value is: 100001111010001101111110001111010111100001
The Binary value after string conversion is: Chocka


In [51]:
# Python 3 program to convert
# string into binary string

# utility function
def strToBinary(s):
	bin_conv = []

	for c in s:
		
		# convert each char to
		# ASCII value
		ascii_val = ord(c)
		
		# Convert ASCII value to binary
		binary_val = bin(ascii_val)
		bin_conv.append(binary_val[2:])
		
	return (' '.join(bin_conv))

# Driver Code
if __name__ == '__main__':
	s = 'Chocka'

print (strToBinary(s))

# This code is contributed
# by Vikas Chitturi


1000011 1101000 1101111 1100011 1101011 1100001
